## Utiização da Biblioteca Numpy

In [36]:
# Importando a biblioteca numpy
!pip install numpy
import numpy as np

## Criação de arrays

In [37]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [38]:
# Criação de um array 1D: [1,2,3]
l = [1,2,3]
x = np.array(l)
print('x:',x)
print('shape:', x.shape)

x: [1 2 3]
shape: (3,)


In [39]:
# Verificando o tipo de dado
type(x)

numpy.ndarray

In [40]:
# Criação de um array 2D: listas aninhadas
l= [[1,2],[3,4]]
x = np.array(l)
print('x:\n',x)
print('shape:', x.shape)

x:
 [[1 2]
 [3 4]]
shape: (2, 2)


In [41]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [42]:
# arrey contendo apenas 0´s
dim = (2,2) #(linhas, colunas)
x = np.zeros(dim)
print('x:\n', x)
print('shape:', x.shape)

x:
 [[0. 0.]
 [0. 0.]]
shape: (2, 2)


In [43]:
# array contendo apenas 1´s
size = (2,2) # (linhas, colunas)
x = np.ones(size)
print('x:\n', x)
print('shape:', x.shape)

x:
 [[1. 1.]
 [1. 1.]]
shape: (2, 2)


In [44]:
# Criação de valores dentro de um intervalo
# Valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)
print('x:', x)
print('shape:', x.shape)

x: [ 5.  7.  9. 11. 13. 15.]
shape: (6,)


In [45]:
# Criação da matriz identificada
n = 4
x = np.eye(n)
print('x:\n', x)
print('shape:', x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape: (4, 4)


In [46]:
# Criando valores aleatórios
# np.random.seed(10)

x= np.random.random(size=(2,3))
print('x:', x)
print('shape:', x.shape)

x: [[0.30065155 0.65618236 0.2543602 ]
 [0.2548225  0.44924675 0.25753218]]
shape: (2, 3)


## Indexação de arrays

In [47]:
# Os indices no python vão de 0 a n-1,
# onde n é o tamanho da dimensão

x = np.linspace(start=10, stop=100, num=10)
print('x:', x)
print('shape:', x.shape)


x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [48]:
# Extração de elementos

print('x:', x)
print('primeiro elemento', x[0])
print('segundo elemento', x[1])
print('último elemento', x[9])
print('último elemento', x[-1])


x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento 10.0
segundo elemento 20.0
último elemento 100.0
último elemento 100.0


In [49]:
# slicing: extração de subarrays

print('x:', x)
print('dois primeiros elementos', x[0:2])
print('dois primeiros elementos', x[:2])
print('dois últimos elementos', x[-2:])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos [10. 20.]
dois primeiros elementos [10. 20.]
dois últimos elementos [ 90. 100.]


In [50]:
# slicing em array 2D (matrizes)

x = x.reshape(2, 5) # reshape de x para 2 linhas e 5 colunas
print('x:\n', x)

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [51]:
# extração de elementos

print('primeira linha, segunda coluna:', x[0, 1])
print('segunda linha penultima coluna: ', x[1, -2])
print('ultima linha, ultima coluna: ', x[1, 4])
print('ultima linha, ultima coluna: ', x[-1, -1])

primeira linha, segunda coluna: 20.0
segunda linha penultima coluna:  90.0
ultima linha, ultima coluna:  100.0
ultima linha, ultima coluna:  100.0


In [52]:
# slicing: extração de subarrays

print('x:\n', x)
print('primeira linha inteira: ', x[0, :])
print('primeira linha, seginda coluna a quarta coluna: ', x[0, 1:4])
print('ultima coluna inteira:\n ', x[:, [-1]])

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primeira linha inteira:  [10. 20. 30. 40. 50.]
primeira linha, seginda coluna a quarta coluna:  [20. 30. 40.]
ultima coluna inteira:
  [[ 50.]
 [100.]]


In [53]:
# atenção com compartilhamento de memoria em subarrays!

x = np.array([1,2,3])
print('x antes: ', x)
y = x[:2]
y[0] = -100 # alteração do valor em y altara o valor de x
print('x depois: ', x)

x antes:  [1 2 3]
x depois:  [-100    2    3]


In [54]:
# atenção com compartilhamento de memroria em subarreys!!

x = np.array([1, 2, 3])
print('x antes: ', x)
y = x[:2].copy()
y[0] = -100 # alteração do valor emy altera o valor de x
print('x depois: ', x)

x antes:  [1 2 3]
x depois:  [1 2 3]


## Operações Aritiméticas

In [55]:
# Operações aritimeticas elemento a elemento 
x = np.ones((2,2))
y = np.eye(2)
print('x; \n', x)
print('y: \n', y)


x; 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [56]:
# soma 
print('soma de dois arrays: \n', x + y)
print('subtração com float/int: \n', x + 2) # broadcasting


soma de dois arrays: 
 [[2. 1.]
 [1. 2.]]
subtração com float/int: 
 [[3. 3.]
 [3. 3.]]


In [57]:
# subtração
print('soma de dois arrays: \n', x - y)
print('subtração com float/int: \n', x - 2) # broadcasting

soma de dois arrays: 
 [[0. 1.]
 [1. 0.]]
subtração com float/int: 
 [[-1. -1.]
 [-1. -1.]]


In [58]:
# divisão
print('soma de dois arrays: \n', x / y)
print('subtração com float/int: \n', x / 2) # broadcasting

soma de dois arrays: 
 [[ 1. inf]
 [inf  1.]]
subtração com float/int: 
 [[0.5 0.5]
 [0.5 0.5]]


C:\Users\Administrador\AppData\Local\Temp\ipykernel_1388\3036059388.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print('soma de dois arrays: \n', x / y)


In [59]:
# quando o broadcasting não funciona
np.array([1, 2, 3]) + np.array([1, 2]) # para o broadcasting funcionar tem que estar assim 'np.array([1])'

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# soma, subtração e divisão
print('combinação de operações:\n', (x+y)/(x-2))

combinação de operações:
 [[-2. -1.]
 [-1. -2.]]


## Funções aritiméticas: multiplicação

In [ ]:
# multiplicação elemento a elemento
print('x: \n', x)
print('y: \n', y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [ ]:
# multiplicação
print('multiplicação de dois arrays: \n', x * y)
print('multiplicação com float/int: \n', x * 2) # broadcasting

multiplicação de dois arrays: 
 [[1. 0.]
 [0. 1.]]
multiplicação com float/int: 
 [[2. 2.]
 [2. 2.]]


In [ ]:
# multiplicação matricial
print('multiplicação matricial (n.dot): \n', np.dot(x, y))
print('multiplicação matricial (@): \n', x @ y)
print('multiplicação matricial (.dot): \n', x.dot(y))

multiplicação matricial (n.dot): 
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@): 
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (.dot): 
 [[1. 1.]
 [1. 1.]]


In [62]:
"""
Exemplo:
solução de um sistema de equações:
    a + 2*b = 7
    3*a - 2*b = -11
    
    Solução analitica: (a, b) = (-1, 4)
Matricialmente, este problema tem a seguinte forma:
    Ax = c, onde:
    - x = [a, b]
    - A = [[1, 2], [3, -2]]
    - c = [7, -11]
solução numerica: x = inv(A) @ c,
"""

# difeininção do problema
A = np.array([[1, 2], [3, -2]])
c = np.array([[7],[-11]])
print('A: \n', A)
print('c: \n', c)

A: 
 [[ 1  2]
 [ 3 -2]]
c: 
 [[  7]
 [-11]]


In [63]:
"""
                            Ax = c
                        [1  2  [a  =  [7
                         3 -2]  b]    -11]

                         x = A-¹c                               
"""

# solução
x = np.dot(np.linalg.inv(A), c)
#x = np.linalg.inv(A) @ c
print('(a, b): ', x.ravel())

(a, b):  [-1.  4.]


## Comparações e Indexação Booleana

In [3]:
# Comparações menor/ menor ou igual:
# comparações booleanas
import numpy as np

A= np.array([1,2,3])
B = np.array([2,0,2])
S = 3

In [4]:
# menor
print('Comparação menor: ')
print(A < B)
print(A < S)

Comparação menor: 
[ True False False]
[ True  True False]


In [5]:
# menor ou igual
print("Comparação menor ou igual")
print(A <= B)
print(A <= S)

Comparação menor ou igual
[ True False False]
[ True  True  True]


In [6]:
# igual
print('Comparação de igualdade: ')
print(A == B)
print(A == S)

Comparação de igualdade: 
[False False False]
[False False  True]


## Indexação Booleana

In [7]:
# Operações de filtro

# Indexação booleana: um novo subrray contendo uma cópia dos elementos em que a condição de verificação se aplica

cond = A <= 2
D = A[cond]
print('A: ', A)
print('Condição: ', cond)
print('D: ', D)

A:  [1 2 3]
Condição:  [ True  True False]
D:  [1 2]


## Comparações

In [10]:
# Criação dos arrays

x = np.array([[1,2],[3,4]])
y = np.array([1.4, 3.5])
print('x: \n', x)
print('y: \n', y)

x: 
 [[1 2]
 [3 4]]
y: 
 [1.4 3.5]


In [11]:
# Comparações ponto a ponto

print('Comparação de um array com um escalar (>): \n', x > 2)
print('Comparação de um array com um escalar (>=): \n', x >= 2)
print('Comparação de um array com um escalar (<): \n', x < 2)
print('Comparação de um array com um escalar (<=): \n', x <= 2)
print('Comparação entre arrays (==): \n', x == x)
print('Comparação entre arrays (>): \n', x > x)
print('Comparação entre arrays (>): \n', x > y) # Broadcasting 


Comparação de um array com um escalar (>): 
 [[False False]
 [ True  True]]
Comparação de um array com um escalar (>=): 
 [[False  True]
 [ True  True]]
Comparação de um array com um escalar (<): 
 [[ True False]
 [False False]]
Comparação de um array com um escalar (<=): 
 [[ True  True]
 [False False]]
Comparação entre arrays (==): 
 [[ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[False False]
 [False False]]
Comparação entre arrays (>): 
 [[False False]
 [ True  True]]


## Indexação Booleana

In [13]:
# Idexação booleana

x = np.array([[1, 2, 7],
             [3, 11, 21],
             [42, 8, 9]])
print('x: \n', x)

x: 
 [[ 1  2  7]
 [ 3 11 21]
 [42  8  9]]


In [16]:
# Indexação booleana: retornar o numero de elementos maiores que k
k = 10
cond = x > k
print('condição: \n', cond)
print(f'Elementos maiores que {k}: ', x[cond])
print(f'Números de elementos maiores que {k}: ', len(x[cond]))

condição: 
 [[False False False]
 [False  True  True]
 [ True False False]]
Elementos maiores que 10:  [11 21 42]
Número de elementos maiores que 10:  3


In [17]:
# Indexação booleana: extração dos números pares
cond = x % 2 == 0 # números pares
print('Condição: \n', cond)
print('Números pares: ', x[cond])

Condição: 
 [[False  True False]
 [False False False]
 [ True  True False]]
Números pares:  [ 2 42  8]


In [18]:
# Indexaçõ booleana: extração dos números impares
cond = x % 2 == 1 # números impares
print('Condição: \n', cond)
print('Numeros impares: \n', x[cond])

Condição: 
 [[ True False  True]
 [ True  True  True]
 [False False  True]]
Numeros impares: 
 [ 1  7  3 11 21  9]


## Dicas Gerais Numpy

In [19]:
# array
x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])
print('x: \n', x)

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [23]:
#reshape: transformar a matriz em um vetor coluna
# (3, 3) virar (9, 1): 3 * 3 = 9*1 = 9
print('Transfomação de um vetor coluna: \n', x.reshape(9, 1))

Transfomação de um vetor coluna: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [24]:
# Transposição de amtriz
print('x: transposta: \n', x.T)

x: transposta: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [25]:
# np.sum: soma em um dado eixo, axis = {0: linha, 1: coluna}
print('x: \n', x)
print('Soma de todos elementos de x: ', np.sum(x))
print('Soma de x ao longo das linhas: ', np.sum(x, axis=0))
print('Soma de x ao longo das colunas: ', np.sum(x, axis=1))


x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
Soma de todos elementos de x:  106
Soma de x ao longo das linhas:  [47 22 37]
Soma de x ao longo das colunas:  [11 36 59]
